[build]
command = "composer install --no-dev && npm run build" # Correct order!
publish = "public"
functions = "functions"

[build.environment]
PHP_VERSION = "8.1"
NODE_VERSION = "18.17.0"

[[redirects]]
from = "/*"
to = "/index.php"
status = 200

[functions]
directory = "functions"
